fieldLayouts:
  4bc79092-b97e-4725-8513-2694c4a1d3cf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 437d9dea-b421-4151-a76c-6bf494644c0f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a907184e-1b03-4883-a673-9f6ef4b491f6 # kleding naam
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b73b238b-bcc4-4648-b2a9-70dbad823f78
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: da909e0d-92bd-4bf2-b37f-940584bc6ff5 # kleding image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b57eb65-c9f4-4e0d-91b8-90da66bb24c8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8078f98f-bb62-4b71-9f1c-98ffa0f6b8fd # maat
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98372682-166c-4a4d-8aac-45daf0bd542b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7e5f7b07-ce22-4495-b573-b3155cfa22c2 # prijs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc6d2352-630f-441a-8078-89e74c044774
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2cc6b021-9607-44af-840f-1c67e7e13a2b
        userCondition: null
handle: kledingstuk
hasTitleField: true
name: kledingstuk
section: 739264b5-2615-4038-b1e8-89cd58a633e1 # kleding
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
